---
#
# Install/run elasticsearch
#

- name: Install libsemanage-python and dependencies
  yum:
    name: libsemanage-python
  become: true

- name: Install java-8
  yum:
    name: java-1.8.0-openjdk-devel
  become: true

- name: Import the Elasticsearch GPG Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install elasticsearch
  yum:
    name: elasticsearch
    enablerepo: elasticsearch
  become: true

- name: Copy templated elasticsearch.yml
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=elasticsearch
    mode=0660
  become: true
  ignore_errors: true

# this seems like a packaging bug for 6.x
- name: Create log directory structure for ES
  file:
    path: /usr/share/elasticsearch/logs
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755

# another packaging bug, this should be done by RPM
- name: Create datadir for elasticsearch
  file:
    path: /usr/share/elasticsearch/data
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755

- name: Start or restart elasticsearch service
  command: systemctl restart elasticsearch.service
  ignore_errors: true
  when: elasticsearch_updated != 0
  become: true

- name: Setup elasticsearch service to autostart
  service: name=elasticsearch state=started enabled=true
  become: true
